# Generated by Django 4.2.5 on 2023-11-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeauteCartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
