# Generated by Django 4.2.5 on 2023-11-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeauteCartApp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
