# Generated by Django 4.2.5 on 2023-09-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeauteCartApp', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
