# Generated by Django 4.2.5 on 2023-11-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeauteCartApp', '0016_cart1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeauteCartApp.cart1')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeauteCartApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart1',
            name='products',
            field=models.ManyToManyField(through='BeauteCartApp.CartItem1', to='BeauteCartApp.product'),
        ),
    ]
