# Generated by Django 4.2.5 on 2024-01-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeauteCartApp', '0017_cartitem1_cart1_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parlour_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parlour_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
