# Generated by Django 4.2.5 on 2024-01-30 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeauteCartApp', '0018_customuser_parlour_address_customuser_parlour_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beautician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('social_media_links', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True)),
                ('availability', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeup_type', models.CharField(max_length=255)),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portfolio_images', models.ImageField(blank=True, upload_to='portfolio/')),
                ('service_offerings', models.TextField()),
                ('beautician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeauteCartApp.beautician')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('beautician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeauteCartApp.beautician')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeauteCartApp.service')),
            ],
        ),
    ]
