# Generated by Django 4.2.5 on 2024-02-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeauteCartApp', '0020_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portfolio_images', models.ImageField(blank=True, upload_to='portfolio/')),
                ('service_offerings', models.TextField()),
                ('beautician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeauteCartApp.beautician')),
                ('makeup_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeauteCartApp.makeuptype')),
            ],
        ),
    ]
