# Generated by Django 4.2.5 on 2024-02-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeauteCartApp', '0021_makeuptype_service1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('makeup_type', models.CharField(choices=[('Bridal Makeup', 'Bridal Makeup'), ('Engagement Makeup', 'Engagement Makeup'), ('Reception Makeup', 'Reception Makeup'), ('Party Makeup', 'Party Makeup'), ('Mehndi Makeup', 'Mehndi Makeup'), ('Others', 'Others')], max_length=255)),
                ('budget', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('specific_requirements', models.TextField()),
                ('beautician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeauteCartApp.beautician')),
            ],
        ),
    ]
