# Generated by Django 4.2.5 on 2024-02-29 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeauteCartApp', '0022_customizebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizebooking',
            name='beautician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
